// Header file for the ColorMatch application
// This file is generated by the ColorMatch Application in Learn Mode

// Calibration data
sensorData sdBlack = { 7770, 6720, 8840 };
sensorData sdWhite = { 54390, 51740, 69490 };

// Color Table for matching
typedef struct
{
  char    name[9];  // color name 8+nul
  colorData rgb;    // RGB value
} colorTable;

colorTable ct[] = 
{
  {"RED", {23, 1, 2} },
  {"BLUE", {2, 11, 25} },
};
	
